// <auto-generated />
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationContextDb))]
    [Migration("20250315064224_AddClinicToDB")]
    partial class AddClinicToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "New York, NY",
                            Name = "Sunrise Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Los Angeles, CA",
                            Name = "Greenwood Family Clinic"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Chicago, IL",
                            Name = "Wellness Care Center"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Houston, TX",
                            Name = "Downtown Medical"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Phoenix, AZ",
                            Name = "CarePlus Clinic"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Philadelphia, PA",
                            Name = "Healthy Life Clinic"
                        },
                        new
                        {
                            Id = 7,
                            Location = "San Antonio, TX",
                            Name = "Pine Tree Health"
                        },
                        new
                        {
                            Id = 8,
                            Location = "San Diego, CA",
                            Name = "Evergreen Medical"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Dallas, TX",
                            Name = "Community Care Center"
                        },
                        new
                        {
                            Id = 10,
                            Location = "San Jose, CA",
                            Name = "Healing Hands Clinic"
                        },
                        new
                        {
                            Id = 11,
                            Location = "Austin, TX",
                            Name = "Maple Leaf Clinic"
                        },
                        new
                        {
                            Id = 12,
                            Location = "Jacksonville, FL",
                            Name = "Sunflower Family Practice"
                        },
                        new
                        {
                            Id = 13,
                            Location = "San Francisco, CA",
                            Name = "Oakwood Health Services"
                        },
                        new
                        {
                            Id = 14,
                            Location = "Columbus, OH",
                            Name = "Blue Ridge Medical"
                        },
                        new
                        {
                            Id = 15,
                            Location = "Fort Worth, TX",
                            Name = "Riverfront Healthcare"
                        },
                        new
                        {
                            Id = 16,
                            Location = "Charlotte, NC",
                            Name = "Hopewell Medical Center"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Indianapolis, IN",
                            Name = "Summit Medical Group"
                        },
                        new
                        {
                            Id = 18,
                            Location = "Seattle, WA",
                            Name = "Horizon Health"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Denver, CO",
                            Name = "Willow Creek Clinic"
                        },
                        new
                        {
                            Id = 20,
                            Location = "Boston, MA",
                            Name = "Silver Lake Health"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
