// <auto-generated />
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationContextDb))]
    partial class ApplicationContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "New York, NY",
                            Name = "Sunrise Health Clinic"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Los Angeles, CA",
                            Name = "Greenwood Family Clinic"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Chicago, IL",
                            Name = "Wellness Care Center"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Houston, TX",
                            Name = "Downtown Medical"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Phoenix, AZ",
                            Name = "CarePlus Clinic"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Philadelphia, PA",
                            Name = "Healthy Life Clinic"
                        },
                        new
                        {
                            Id = 7,
                            Location = "San Antonio, TX",
                            Name = "Pine Tree Health"
                        },
                        new
                        {
                            Id = 8,
                            Location = "San Diego, CA",
                            Name = "Evergreen Medical"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Dallas, TX",
                            Name = "Community Care Center"
                        },
                        new
                        {
                            Id = 10,
                            Location = "San Jose, CA",
                            Name = "Healing Hands Clinic"
                        },
                        new
                        {
                            Id = 11,
                            Location = "Austin, TX",
                            Name = "Maple Leaf Clinic"
                        },
                        new
                        {
                            Id = 12,
                            Location = "Jacksonville, FL",
                            Name = "Sunflower Family Practice"
                        },
                        new
                        {
                            Id = 13,
                            Location = "San Francisco, CA",
                            Name = "Oakwood Health Services"
                        },
                        new
                        {
                            Id = 14,
                            Location = "Columbus, OH",
                            Name = "Blue Ridge Medical"
                        },
                        new
                        {
                            Id = 15,
                            Location = "Fort Worth, TX",
                            Name = "Riverfront Healthcare"
                        },
                        new
                        {
                            Id = 16,
                            Location = "Charlotte, NC",
                            Name = "Hopewell Medical Center"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Indianapolis, IN",
                            Name = "Summit Medical Group"
                        },
                        new
                        {
                            Id = 18,
                            Location = "Seattle, WA",
                            Name = "Horizon Health"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Denver, CO",
                            Name = "Willow Creek Clinic"
                        },
                        new
                        {
                            Id = 20,
                            Location = "Boston, MA",
                            Name = "Silver Lake Health"
                        });
                });

            modelBuilder.Entity("Model.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SelectedTimeSlots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specailized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicID");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicID = 0,
                            Description = "Expert in Cardiology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Steven Young",
                            Price = 150.0,
                            SelectedTimeSlots = "1,21",
                            Specailized = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            ClinicID = 0,
                            Description = "Expert in Dermatology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. James Jackson",
                            Price = 120.0,
                            SelectedTimeSlots = "2,22",
                            Specailized = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            ClinicID = 0,
                            Description = "Expert in Neurology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Paul Wright",
                            Price = 180.0,
                            SelectedTimeSlots = "3,23",
                            Specailized = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            ClinicID = 0,
                            Description = "Expert in Pediatrics.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Emily Johnson",
                            Price = 110.0,
                            SelectedTimeSlots = "4,24",
                            Specailized = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            ClinicID = 0,
                            Description = "Expert in Orthopedics.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Patricia Thomas",
                            Price = 200.0,
                            SelectedTimeSlots = "5,25",
                            Specailized = "Orthopedics"
                        },
                        new
                        {
                            Id = 6,
                            ClinicID = 0,
                            Description = "Expert in Gynecology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Emily Johnson",
                            Price = 130.0,
                            SelectedTimeSlots = "6,26",
                            Specailized = "Gynecology"
                        },
                        new
                        {
                            Id = 7,
                            ClinicID = 0,
                            Description = "Expert in General Medicine.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. John Smith",
                            Price = 100.0,
                            SelectedTimeSlots = "7,27",
                            Specailized = "General Medicine"
                        },
                        new
                        {
                            Id = 8,
                            ClinicID = 0,
                            Description = "Expert in ENT.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Patricia Thomas",
                            Price = 140.0,
                            SelectedTimeSlots = "8,28",
                            Specailized = "ENT"
                        },
                        new
                        {
                            Id = 9,
                            ClinicID = 0,
                            Description = "Expert in Urology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Steven Young",
                            Price = 160.0,
                            SelectedTimeSlots = "9,29",
                            Specailized = "Urology"
                        },
                        new
                        {
                            Id = 10,
                            ClinicID = 0,
                            Description = "Expert in Gastroenterology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Barbara White",
                            Price = 170.0,
                            SelectedTimeSlots = "10,30",
                            Specailized = "Gastroenterology"
                        },
                        new
                        {
                            Id = 11,
                            ClinicID = 0,
                            Description = "Expert in Oncology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Paul Wright",
                            Price = 220.0,
                            SelectedTimeSlots = "11,31",
                            Specailized = "Oncology"
                        },
                        new
                        {
                            Id = 12,
                            ClinicID = 0,
                            Description = "Expert in Psychiatry.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Paul Wright",
                            Price = 130.0,
                            SelectedTimeSlots = "12,32",
                            Specailized = "Psychiatry"
                        },
                        new
                        {
                            Id = 13,
                            ClinicID = 0,
                            Description = "Expert in Nephrology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Jennifer Scott",
                            Price = 190.0,
                            SelectedTimeSlots = "13,33",
                            Specailized = "Nephrology"
                        },
                        new
                        {
                            Id = 14,
                            ClinicID = 0,
                            Description = "Expert in Endocrinology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Barbara White",
                            Price = 140.0,
                            SelectedTimeSlots = "14,34",
                            Specailized = "Endocrinology"
                        },
                        new
                        {
                            Id = 15,
                            ClinicID = 0,
                            Description = "Expert in Radiology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. John Smith",
                            Price = 180.0,
                            SelectedTimeSlots = "15,35",
                            Specailized = "Radiology"
                        },
                        new
                        {
                            Id = 16,
                            ClinicID = 0,
                            Description = "Expert in Rheumatology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Michael Brown",
                            Price = 160.0,
                            SelectedTimeSlots = "16,36",
                            Specailized = "Rheumatology"
                        },
                        new
                        {
                            Id = 17,
                            ClinicID = 0,
                            Description = "Expert in Plastic Surgery.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Susan Clark",
                            Price = 250.0,
                            SelectedTimeSlots = "17,37",
                            Specailized = "Plastic Surgery"
                        },
                        new
                        {
                            Id = 18,
                            ClinicID = 0,
                            Description = "Expert in Pulmonology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Susan Clark",
                            Price = 170.0,
                            SelectedTimeSlots = "18,38",
                            Specailized = "Pulmonology"
                        },
                        new
                        {
                            Id = 19,
                            ClinicID = 0,
                            Description = "Expert in Hematology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. Robert Anderson",
                            Price = 200.0,
                            SelectedTimeSlots = "19,39",
                            Specailized = "Hematology"
                        },
                        new
                        {
                            Id = 20,
                            ClinicID = 0,
                            Description = "Expert in Ophthalmology.\nProvides top-notch care.",
                            ImageUrl = "",
                            Name = "Dr. David Wilson",
                            Price = 150.0,
                            SelectedTimeSlots = "20,40",
                            Specailized = "Ophthalmology"
                        });
                });

            modelBuilder.Entity("Model.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Avaiable")
                        .HasColumnType("bit");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("timeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avaiable = true,
                            Date = "2025-03-01",
                            DoctorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Avaiable = true,
                            Date = "2025-03-02",
                            DoctorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Avaiable = true,
                            Date = "2025-03-03",
                            DoctorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Avaiable = true,
                            Date = "2025-03-04",
                            DoctorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Avaiable = true,
                            Date = "2025-03-05",
                            DoctorId = 5
                        },
                        new
                        {
                            Id = 6,
                            Avaiable = true,
                            Date = "2025-03-06",
                            DoctorId = 6
                        },
                        new
                        {
                            Id = 7,
                            Avaiable = true,
                            Date = "2025-03-07",
                            DoctorId = 7
                        },
                        new
                        {
                            Id = 8,
                            Avaiable = true,
                            Date = "2025-03-08",
                            DoctorId = 8
                        },
                        new
                        {
                            Id = 9,
                            Avaiable = true,
                            Date = "2025-03-09",
                            DoctorId = 9
                        },
                        new
                        {
                            Id = 10,
                            Avaiable = true,
                            Date = "2025-03-10",
                            DoctorId = 10
                        },
                        new
                        {
                            Id = 11,
                            Avaiable = true,
                            Date = "2025-03-11",
                            DoctorId = 11
                        },
                        new
                        {
                            Id = 12,
                            Avaiable = true,
                            Date = "2025-03-12",
                            DoctorId = 12
                        },
                        new
                        {
                            Id = 13,
                            Avaiable = true,
                            Date = "2025-03-13",
                            DoctorId = 13
                        },
                        new
                        {
                            Id = 14,
                            Avaiable = true,
                            Date = "2025-03-14",
                            DoctorId = 14
                        },
                        new
                        {
                            Id = 15,
                            Avaiable = true,
                            Date = "2025-03-15",
                            DoctorId = 15
                        },
                        new
                        {
                            Id = 16,
                            Avaiable = true,
                            Date = "2025-03-16",
                            DoctorId = 16
                        },
                        new
                        {
                            Id = 17,
                            Avaiable = true,
                            Date = "2025-03-17",
                            DoctorId = 17
                        },
                        new
                        {
                            Id = 18,
                            Avaiable = true,
                            Date = "2025-03-18",
                            DoctorId = 18
                        },
                        new
                        {
                            Id = 19,
                            Avaiable = true,
                            Date = "2025-03-19",
                            DoctorId = 19
                        },
                        new
                        {
                            Id = 20,
                            Avaiable = true,
                            Date = "2025-03-20",
                            DoctorId = 20
                        },
                        new
                        {
                            Id = 21,
                            Avaiable = true,
                            Date = "2025-03-21",
                            DoctorId = 1
                        },
                        new
                        {
                            Id = 22,
                            Avaiable = true,
                            Date = "2025-03-22",
                            DoctorId = 2
                        },
                        new
                        {
                            Id = 23,
                            Avaiable = true,
                            Date = "2025-03-23",
                            DoctorId = 3
                        },
                        new
                        {
                            Id = 24,
                            Avaiable = true,
                            Date = "2025-03-24",
                            DoctorId = 4
                        },
                        new
                        {
                            Id = 25,
                            Avaiable = true,
                            Date = "2025-03-25",
                            DoctorId = 5
                        },
                        new
                        {
                            Id = 26,
                            Avaiable = true,
                            Date = "2025-03-26",
                            DoctorId = 6
                        },
                        new
                        {
                            Id = 27,
                            Avaiable = true,
                            Date = "2025-03-27",
                            DoctorId = 7
                        },
                        new
                        {
                            Id = 28,
                            Avaiable = true,
                            Date = "2025-03-28",
                            DoctorId = 8
                        },
                        new
                        {
                            Id = 29,
                            Avaiable = true,
                            Date = "2025-03-29",
                            DoctorId = 9
                        },
                        new
                        {
                            Id = 30,
                            Avaiable = true,
                            Date = "2025-03-30",
                            DoctorId = 10
                        },
                        new
                        {
                            Id = 31,
                            Avaiable = true,
                            Date = "2025-03-31",
                            DoctorId = 11
                        },
                        new
                        {
                            Id = 32,
                            Avaiable = true,
                            Date = "2025-03-01",
                            DoctorId = 12
                        },
                        new
                        {
                            Id = 33,
                            Avaiable = true,
                            Date = "2025-03-02",
                            DoctorId = 13
                        },
                        new
                        {
                            Id = 34,
                            Avaiable = true,
                            Date = "2025-03-03",
                            DoctorId = 14
                        },
                        new
                        {
                            Id = 35,
                            Avaiable = true,
                            Date = "2025-03-04",
                            DoctorId = 15
                        },
                        new
                        {
                            Id = 36,
                            Avaiable = true,
                            Date = "2025-03-05",
                            DoctorId = 16
                        },
                        new
                        {
                            Id = 37,
                            Avaiable = true,
                            Date = "2025-03-06",
                            DoctorId = 17
                        },
                        new
                        {
                            Id = 38,
                            Avaiable = true,
                            Date = "2025-03-07",
                            DoctorId = 18
                        },
                        new
                        {
                            Id = 39,
                            Avaiable = true,
                            Date = "2025-03-08",
                            DoctorId = 19
                        },
                        new
                        {
                            Id = 40,
                            Avaiable = true,
                            Date = "2025-03-09",
                            DoctorId = 20
                        });
                });

            modelBuilder.Entity("Model.Doctor", b =>
                {
                    b.HasOne("Model.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Model.TimeSlot", b =>
                {
                    b.HasOne("Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
